### ISSUE TITLE
Minor updates checklist

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/vector-analysis-syracuse-lesson#7]
- [x] remove the call to `library(magrittr)`
- [x] add `library(spatialreg)` to code
- [x] replace `read_sf` with `st_read`
- [x] There are a couple places where maybe old sf syntax is used that could be updated

**Comment by qdread** [comment]
Everything addressed in 3c503d1
